gem 'minitest'
require 'minitest/autorun'
require 'minitest/spec'
require './test/support/command_sequence'
require './test/support/setup_easy_repl'
require './test/support/teardown_easy_repl'
require './test/support/before_input_easy_repl'
require './test/support/after_input_easy_repl'
